import os
import logging
import json
import subprocess
from dotenv import load_dotenv
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes, CallbackQueryHandler, MessageHandler, filters
from telegram.error import BadRequest
import db

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

load_dotenv()

if os.getenv("GITHUB_TOKEN") and not os.getenv("GH_TOKEN"):
    os.environ["GH_TOKEN"] = os.getenv("GITHUB_TOKEN")

TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TARGET_REPO = os.getenv("TARGET_REPO")
ISSUE_LABEL = os.getenv("ISSUE_LABEL", "jules-task")

def get_main_keyboard():
    paused = db.is_paused()
    pause_label = "▶️ Resume" if paused else "⏸ Pause"
    pause_callback = "resume" if paused else "pause"
    
    keyboard = [
        [
            InlineKeyboardButton("📊 Status", callback_data="status"),
            InlineKeyboardButton("🔄 Sync Backlog", callback_data="sync")
        ],
        [
            InlineKeyboardButton(pause_label, callback_data=pause_callback),
            InlineKeyboardButton("➕ Add Task", callback_data="ask_task")
        ],
        [InlineKeyboardButton("🗑 Clear Finished", callback_data="clear_terminal")]
    ]
    return InlineKeyboardMarkup(keyboard)

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "🐙 *Octo-Jules Control Center*\n\nManage your autonomous coding agent from here.",
        parse_mode="Markdown",
        reply_markup=get_main_keyboard()
    )

async def button_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()
    
    data = query.data
    
    try:
        if data == "status":
            conn = db.get_connection()
            try:
                with conn.cursor() as cursor:
                    cursor.execute("SELECT issue_title, state FROM sessions ORDER BY created_at DESC LIMIT 5")
                    rows = cursor.fetchall()
            finally:
                conn.close()
            
            paused = db.is_paused()
            msg = f"*Current State:* {'⏸ PAUSED' if paused else '🚀 RUNNING'}\n\n*Recent Sessions:*\n"
            if not rows:
                msg += "No sessions yet."
            else:
                for row in rows:
                    msg += f"• {row[0]}: `{row[1]}`\n"
            
            await query.edit_message_text(msg, parse_mode="Markdown", reply_markup=get_main_keyboard())

        elif data == "pause":
            db.set_paused(True)
            await query.edit_message_text("⏸ Orchestrator has been *PAUSED*.", parse_mode="Markdown", reply_markup=get_main_keyboard())
            
        elif data == "resume":
            db.set_paused(False)
            await query.edit_message_text("🚀 Orchestrator has been *RESUMED*.", parse_mode="Markdown", reply_markup=get_main_keyboard())
    except BadRequest:
        # Ignore "Message is not modified" errors
        pass

    if data == "sync":
        try:
            with open("personas.json", "r") as f:
                personas = json.load(f)
        except FileNotFoundError:
            personas = {}
            
        keyboard = []
        keyboard.append([InlineKeyboardButton("🎲 Random", callback_data="run_sync:random")])
        
        row = []
        for key, p in personas.items():
            row.append(InlineKeyboardButton(f"👤 {p['name']}", callback_data=f"run_sync:{key}"))
            if len(row) == 2:
                keyboard.append(row)
                row = []
        if row:
            keyboard.append(row)
        
        keyboard.append([InlineKeyboardButton("🔙 Cancel", callback_data="status")])
        
        await query.edit_message_text("Select a team member to brainstorm with:", reply_markup=InlineKeyboardMarkup(keyboard))

    elif data.startswith("run_sync:"):
        persona_key = data.split(":")[1]
        cmd = ["python3", "backlog_sustainer.py", "--force"]
        
        target_name = "Random Agent"
        if persona_key != "random":
            cmd.extend(["--persona", persona_key])
            target_name = persona_key
            
        await query.edit_message_text(f"🧠 {target_name} is brainstorming new tasks...")
        
        try:
            # Using list format for secure argument passing
            subprocess.run(cmd, check=True)
            await query.message.reply_text(f"✅ Ideas generated by {target_name}!")
        except Exception as e:
            await query.message.reply_text(f"❌ Generation failed: {e}")
            
        # Return to main menu
        await query.message.reply_text("Control Center:", reply_markup=get_main_keyboard())

    elif data == "ask_task":
        await query.message.reply_text("Send the task in this format:\n`/add_task Title:Body`", parse_mode="Markdown")

    elif data == "clear_terminal":
        # Optional utility to hide old merged items from dashboard/bot
        await query.message.reply_text("Cleaning up terminal states in database...")
        # Add logic here if needed

async def add_task(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not context.args:
        await update.message.reply_text("Usage: /add_task <title>:<body_optional>")
        return
        
    text = " ".join(context.args)
    if ":" in text:
        title, body = text.split(":", 1)
    else:
        title, body = text, ""
        
    cmd = f'gh issue create --repo {TARGET_REPO} --title "{title.strip()}" --body "{body.strip()}" --label "{ISSUE_LABEL}"'
    try:
        result = subprocess.run(cmd, shell=True, check=True, capture_output=True, text=True)
        await update.message.reply_text(f"✅ Issue created: {result.stdout.strip()}")
    except Exception as e:
        await update.message.reply_text(f"❌ Failed to create issue: {e}")

async def pick_issue(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not context.args:
        await update.message.reply_text("Usage: /pick <issue_number>")
        return
    
    try:
        issue_number = int(context.args[0])
        db.set_setting('next_issue', issue_number)
        await update.message.reply_text(f"✅ Issue #{issue_number} selected. Jules will start shortly.")
    except ValueError:
        await update.message.reply_text("❌ Please provide a valid issue number.")
    except Exception as e:
        await update.message.reply_text(f"❌ Error: {e}")

if __name__ == '__main__':
    if not TOKEN:
        print("Error: TELEGRAM_BOT_TOKEN not set.")
    else:
        app = ApplicationBuilder().token(TOKEN).build()
        app.add_handler(CommandHandler("start", start))
        app.add_handler(CommandHandler("add_task", add_task))
        app.add_handler(CommandHandler("pick", pick_issue))
        app.add_handler(CommandHandler("status", lambda u, c: start(u, c))) # Alias /status to /start for keyboard
        app.add_handler(CallbackQueryHandler(button_handler))
        app.add_handler(MessageHandler(filters.TEXT & (~filters.COMMAND), start))
        
        print("Bot is running...")
        app.run_polling()
